language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - BOOST_PREFIX=$HOME/local LD_LIBRARY_PATH=$BOOST_PREFIX/lib:$LD_LIBRARY_PATH

install:
  - sudo apt-get install libncurses-dev autoconf autoconf-archive automake pkg-config
  - pwd
  - ls -l
  - ls -l ~
  - ls -l /usr/bin/python*
  - which python
  - python -c "import sys; print('\n'.join(sys.path))"
  - python -c "import sys; print(sys.executable); print(sys.version)"
  - env | sort
  - cd ${TRAVIS_BUILD_DIR}/..
  - wget https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.bz2
  - tar -xjf boost_1_69_0.tar.bz2
  - cd boost_1_69_0
  - PY_INCLUDE=$(python -c "import distutils.sysconfig; print(distutils.sysconfig.get_python_inc(True))")
  - echo $PY_INCLUDE
  - "./bootstrap.sh --with-python=`which python` --with-libraries=python --prefix=${BOOST_PREFIX}
    --with-python-root=\"${VIRTUAL_ENV} : ${PY_INCLUDE}\""
  - cat project-config.jam
  - ./b2
  - ./b2 install > /dev/null
  - ls -l ${BOOST_PREFIX}/lib
  - for f in ${BOOST_PREFIX}/lib/*.so ; do echo $f ; ldd $f ; done

script:
  - cd ${TRAVIS_BUILD_DIR}
  - python setup.py install
  - cd ${TRAVIS_BUILD_DIR}/..
  - git clone https://github.com/adelplanque/autotools-extension-example.git
  - cd autotools-extension-example
  - python setup.py configure --with-boost ${BOOST_PREFIX} install
  - cat autoconf/config.log
  - echo -e "\n" | python -c "import waouh; waouh.waouh('Hello world')"
