language: python

python:
  - "2.6"
  - "3.7"

install:
  - sudo apt-get install libboost-python-dev libncuses-dev autocon autoconf-archive aclocal automake
  - pwd
  - ls -l
  - ls -l /usr/bin/python*
  - ls -l /usr/lib/x86_64-linux-gnu/libboost_python*
  - which python

script:
  - python setup.py install --user
  - cd ~
  - git clone https://github.com/adelplanque/autotools-extension-example.git
  - cd autotools-extension-example
  - python setup.py install --user
  - python -c "import woauh"
