language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - sudo apt-get install libboost-python-dev
  - ls -l /usr/bin/python3
  - ls -l /usr/lib/x86_64-linux-gnu/libboost_python*

script:
  - echo "toto"
